### ISSUE TITLE
Administration de Django

### ISSUE THREAD

**Issue by Br-Hmedna** [openfun/hackathon#10]
Bonjour,  
J’ai installé OpenFun en suivant la documentation fournie.
J’ai un souci concernant l'accès à la plateforme admin : http://127.0.0.1:8001/admin/  (django Administration).
Les login et mdp fournis dans la documentation ne fonctionnent pas.
J’ai essayer de créer un superuser en exécutant la commande suivante:

**sudo -u edxapp /edx/bin/python.edxapp /edx/app/edxapp/edx-platform/manage.py lms --settings=aws
createsuperuser --username <user>**

Mais ça ne fonctionne pas non plus. 
Est-ce que quelqu’un a eu le même problème?

**Comment by rmoch** [comment]
si votre VM est correctement instanciée, depuis l'hôte:
`vagrant ssh`  # ouvrez un session ssh dans la vm
`sudo su edxapp`  # passez en utilisateur edxapp
`fun lms.dev shell_plus`    # lancez un shell Python avec les settings FUN

création d'un super utilisateur
`from django.contrib.auth.models import User`
`user = User.objects.create(username="username", is_superuser=True, is_staff=True)`
`user.set_password('password')`
`user.save()`

**Comment by Br-Hmedna** [comment]
Merciii ... ça marche bien ... Super
